/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Chef_Hat.glb --transform 
Files: Chef_Hat.glb [325.17KB] > /home/yoga/Dokumen/game_3d/multi-trade-threejs/mengompresi/Chef_Hat-transformed.glb [389.69KB] (-20%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Chef_Hat-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Bone} />
        </group>
        <group name="Body">
          <skinnedMesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube004.skeleton} />
          <skinnedMesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube004_1.skeleton} />
          <skinnedMesh name="Cube004_2" geometry={nodes.Cube004_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube004_2.skeleton} />
          <skinnedMesh name="Cube004_3" geometry={nodes.Cube004_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube004_3.skeleton} />
          <skinnedMesh name="Cube004_4" geometry={nodes.Cube004_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube004_4.skeleton} />
          <skinnedMesh name="Cube004_5" geometry={nodes.Cube004_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube004_5.skeleton} />
          <skinnedMesh name="Cube004_6" geometry={nodes.Cube004_6.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube004_6.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Chef_Hat-transformed.glb')
