import * as THREE from "three";
import { CHARACTER_CONFIG } from "../../character/character-config";

// Generated by scripts/quarks-to-native.mjs
// Source: Cartoon Blue Gas Explosion.ts
// DO NOT EDIT — re-run the converter to regenerate.

// ─── Bezier/curve helpers ────────────────────────────────────────────────────

function bezier3(
    p0: number,
    p1: number,
    p2: number,
    p3: number,
    t: number,
): number {
    const u = 1 - t;
    return (
        u * u * u * p0 +
        3 * u * u * t * p1 +
        3 * u * t * t * p2 +
        t * t * t * p3
    );
}

interface PiecewiseCurve {
    start: number;
    end: number;
    p0: number;
    p1: number;
    p2: number;
    p3: number;
}

function evalPiecewise(curves: PiecewiseCurve[], t: number): number {
    if (curves.length === 0) return 0;
    for (let i = 0; i < curves.length; i++) {
        const c = curves[i];
        if (t >= c.start && t <= c.end) {
            const nt =
                c.end === c.start ? 0 : (t - c.start) / (c.end - c.start);
            return bezier3(c.p0, c.p1, c.p2, c.p3, nt);
        }
    }
    if (t < curves[0].start)
        return bezier3(
            curves[0].p0,
            curves[0].p1,
            curves[0].p2,
            curves[0].p3,
            0,
        );
    const last = curves[curves.length - 1];
    return bezier3(last.p0, last.p1, last.p2, last.p3, 1.0);
}

interface ColorKey {
    value: { r: number; g: number; b: number };
    pos: number;
}
interface AlphaKey {
    value: number;
    pos: number;
}

function evalAlpha(keys: AlphaKey[], t: number): number {
    for (let i = 0; i < keys.length - 1; i++) {
        if (t <= keys[i + 1].pos) {
            const lt = (t - keys[i].pos) / (keys[i + 1].pos - keys[i].pos);
            return keys[i].value + lt * (keys[i + 1].value - keys[i].value);
        }
    }
    return keys[keys.length - 1].value;
}

function evalColor(keys: ColorKey[], t: number) {
    for (let i = 0; i < keys.length - 1; i++) {
        if (t <= keys[i + 1].pos) {
            const lt = (t - keys[i].pos) / (keys[i + 1].pos - keys[i].pos);
            return {
                r:
                    keys[i].value.r +
                    lt * (keys[i + 1].value.r - keys[i].value.r),
                g:
                    keys[i].value.g +
                    lt * (keys[i + 1].value.g - keys[i].value.g),
                b:
                    keys[i].value.b +
                    lt * (keys[i + 1].value.b - keys[i].value.b),
            };
        }
    }
    return keys[keys.length - 1].value;
}

function rng(a: number, b: number) {
    return a + Math.random() * (b - a);
}

// ─── VFX Class ───────────────────────────────────────────────────────────────

class SingleExplosion {
    private mesh_SparksEmitter: THREE.InstancedMesh | null = null;
    private mesh_GlowEmitter: THREE.InstancedMesh | null = null;
    private mesh_CloudBurstEmitter: THREE.InstancedMesh | null = null;
    private mesh_TrailEmitter: THREE.InstancedMesh | null = null;
    private mesh_SmokeTrailEmitter: THREE.InstancedMesh | null = null;
    private mesh_GasExplosionBlueEmitter: THREE.InstancedMesh | null = null;

    private geo_SparksEmitter: THREE.PlaneGeometry | null = null;
    private geo_GlowEmitter: THREE.PlaneGeometry | null = null;
    private geo_CloudBurstEmitter: THREE.PlaneGeometry | null = null;
    private geo_TrailEmitter: THREE.PlaneGeometry | null = null;
    private geo_SmokeTrailEmitter: THREE.PlaneGeometry | null = null;
    private geo_GasExplosionBlueEmitter: THREE.PlaneGeometry | null = null;

    private mat_SparksEmitter: THREE.ShaderMaterial | null = null;
    private mat_GlowEmitter: THREE.ShaderMaterial | null = null;
    private mat_CloudBurstEmitter: THREE.ShaderMaterial | null = null;
    private mat_TrailEmitter: THREE.ShaderMaterial | null = null;
    private mat_SmokeTrailEmitter: THREE.ShaderMaterial | null = null;
    private mat_GasExplosionBlueEmitter: THREE.ShaderMaterial | null = null;

    private origin = new THREE.Vector3();
    private T = new THREE.Object3D();
    private hideM = new THREE.Matrix4().makeScale(0, 0, 0);
    private age = 0;

    private life_SparksEmitter: number[] = [];
    private maxLife_SparksEmitter: number[] = [];
    private pos_SparksEmitter: THREE.Vector3[] = [];
    private vel_SparksEmitter: THREE.Vector3[] = [];
    private sz_SparksEmitter: number[] = [];
    private rot_SparksEmitter: number[] = [];
    private ptr_SparksEmitter = 0;
    private spawnTimer_SparksEmitter = 0;
    
    
    private life_GlowEmitter: number[] = [];
    private maxLife_GlowEmitter: number[] = [];
    private pos_GlowEmitter: THREE.Vector3[] = [];
    private vel_GlowEmitter: THREE.Vector3[] = [];
    private sz_GlowEmitter: number[] = [];
    private rot_GlowEmitter: number[] = [];
    private ptr_GlowEmitter = 0;
    private spawnTimer_GlowEmitter = 0;
    
    
    private life_CloudBurstEmitter: number[] = [];
    private maxLife_CloudBurstEmitter: number[] = [];
    private pos_CloudBurstEmitter: THREE.Vector3[] = [];
    private vel_CloudBurstEmitter: THREE.Vector3[] = [];
    private sz_CloudBurstEmitter: number[] = [];
    private rot_CloudBurstEmitter: number[] = [];
    private ptr_CloudBurstEmitter = 0;
    private spawnTimer_CloudBurstEmitter = 0;
    
    
    private life_TrailEmitter: number[] = [];
    private maxLife_TrailEmitter: number[] = [];
    private pos_TrailEmitter: THREE.Vector3[] = [];
    private vel_TrailEmitter: THREE.Vector3[] = [];
    private sz_TrailEmitter: number[] = [];
    private rot_TrailEmitter: number[] = [];
    private ptr_TrailEmitter = 0;
    private spawnTimer_TrailEmitter = 0;
    
    
    private life_SmokeTrailEmitter: number[] = [];
    private maxLife_SmokeTrailEmitter: number[] = [];
    private pos_SmokeTrailEmitter: THREE.Vector3[] = [];
    private vel_SmokeTrailEmitter: THREE.Vector3[] = [];
    private sz_SmokeTrailEmitter: number[] = [];
    private rot_SmokeTrailEmitter: number[] = [];
    private ptr_SmokeTrailEmitter = 0;
    private spawnTimer_SmokeTrailEmitter = 0;
    private accumulatedDist_SmokeTrailEmitter: number[] = [];
    
    private life_GasExplosionBlueEmitter: number[] = [];
    private maxLife_GasExplosionBlueEmitter: number[] = [];
    private pos_GasExplosionBlueEmitter: THREE.Vector3[] = [];
    private vel_GasExplosionBlueEmitter: THREE.Vector3[] = [];
    private sz_GasExplosionBlueEmitter: number[] = [];
    private rot_GasExplosionBlueEmitter: number[] = [];
    private ptr_GasExplosionBlueEmitter = 0;
    private spawnTimer_GasExplosionBlueEmitter = 0;
    
    
    public isFinished(): boolean {
        return this.activeFX.length === 0;
    }

    private scene: THREE.Scene;
    private camera: THREE.Camera;
    private activeFX: Array<{ update: (delta: number) => boolean }> = [];
    private tex0: THREE.Texture;
    private tex1: THREE.Texture;
    private tex2: THREE.Texture;
    private tex3: THREE.Texture;

    constructor(scene: THREE.Scene, camera: THREE.Camera) {
        this.scene = scene;
        this.camera = camera;
        const L = new THREE.TextureLoader();
        this.tex0 = L.load("/vfx/cartoon-blue-gas-explosion/tex_0.png");
        this.tex1 = L.load("/vfx/cartoon-blue-gas-explosion/tex_1.png");
        this.tex2 = L.load("/vfx/cartoon-blue-gas-explosion/tex_2.png");
        this.tex3 = L.load("/vfx/cartoon-blue-gas-explosion/tex_3.png");
    }

    public spawn(x: number, y: number, z: number) {
        this.origin.set(x, y, z);
        const T = this.T;
        const hideM = this.hideM;
        const cq = this.camera.quaternion;
        const cfgColor = new THREE.Color(
            CHARACTER_CONFIG.skills.gasExplosion.hudColor,
        );
        this.age = 0;
        const cleanups: (() => void)[] = [];

        // ══════════════════════════════════════════════════════════
        // Emitter: SparksEmitter  (count=23, life=[0.25, 0.35], speed=[12, 28])
        // Texture: tex_0.png  Grid: 1x1
        // ══════════════════════════════════════════════════════════
        const cnt_SparksEmitter = 0;
        let geo_SparksEmitter: THREE.PlaneGeometry;
        let mesh_SparksEmitter: THREE.InstancedMesh;
        let frm_SparksEmitter: Float32Array;
        let opc_SparksEmitter: Float32Array;
        let clr_SparksEmitter: Float32Array;
        let vel_buf_SparksEmitter: Float32Array;
        let off_buf_SparksEmitter: Float32Array;
        let isFirst_SparksEmitter = false;

        if (!this.mesh_SparksEmitter) {
            isFirst_SparksEmitter = true;
            geo_SparksEmitter = new THREE.PlaneGeometry(1, 1);
            this.geo_SparksEmitter = geo_SparksEmitter;
            if (!this.mat_SparksEmitter) {
                this.mat_SparksEmitter = new THREE.ShaderMaterial({
                    uniforms: {
                uMap: { value: this.tex0 },
                speedFactor: { value: 0.01 },
            },
            vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor; attribute vec3 aVelocity; attribute vec3 aOffset;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        uniform float speedFactor;
        void main() {
          float c = mod(aFrame, 1.0); float r = floor(aFrame / 1.0);
          vUv = vec2((c + uv.x) / 1.0, 1.0 - (r + 1.0 - uv.y) / 1.0);
          vOpacity = aOpacity; vColor = aColor;
          vec4 mvPos = modelViewMatrix * vec4(aOffset, 1.0);
          vec3 viewVel = normalMatrix * aVelocity;
          float vlength = length(viewVel);
          float avgSize = (instanceMatrix[0][0] + instanceMatrix[1][1]) * 0.5;
          float sz = length(vec3(instanceMatrix[0][0], instanceMatrix[0][1], instanceMatrix[0][2]));
          mvPos.xyz += position.y * normalize(cross(mvPos.xyz, viewVel)) * sz;
          mvPos.xyz -= (position.x + 0.5) * viewVel * (1.0 + 1.0000 / max(vlength, 0.001)) * sz;
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * mvPos;
        }
      `,
            fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
            transparent: true,
            depthWrite: false,
            side: THREE.DoubleSide,
            blending: THREE.NormalBlending,
                });
            }
            mesh_SparksEmitter = new THREE.InstancedMesh(
                geo_SparksEmitter,
                this.mat_SparksEmitter,
                cnt_SparksEmitter,
            );
            mesh_SparksEmitter.frustumCulled = false;
            this.scene.add(mesh_SparksEmitter);
            this.mesh_SparksEmitter = mesh_SparksEmitter;

            const frm_arr = new Float32Array(cnt_SparksEmitter);
            const opc_arr = new Float32Array(cnt_SparksEmitter);
            const clr_arr = new Float32Array(cnt_SparksEmitter * 3);
            mesh_SparksEmitter.geometry.setAttribute("aFrame", new THREE.InstancedBufferAttribute(frm_arr, 1));
            mesh_SparksEmitter.geometry.setAttribute("aOpacity", new THREE.InstancedBufferAttribute(opc_arr, 1));
            mesh_SparksEmitter.geometry.setAttribute("aColor", new THREE.InstancedBufferAttribute(clr_arr, 3));
            frm_SparksEmitter = frm_arr;
            opc_SparksEmitter = opc_arr;
            clr_SparksEmitter = clr_arr;
            const vel_arr = new Float32Array(cnt_SparksEmitter * 3);
            const off_arr = new Float32Array(cnt_SparksEmitter * 3);
            mesh_SparksEmitter.geometry.setAttribute("aVelocity", new THREE.InstancedBufferAttribute(vel_arr, 3));
            mesh_SparksEmitter.geometry.setAttribute("aOffset", new THREE.InstancedBufferAttribute(off_arr, 3));
            vel_buf_SparksEmitter = vel_arr;
            off_buf_SparksEmitter = off_arr;
            for (let i = 0; i < cnt_SparksEmitter; i++) {
                this.life_SparksEmitter.push(1.0);
                this.maxLife_SparksEmitter.push(1.0);
                this.pos_SparksEmitter.push(new THREE.Vector3(x, y, z));
                this.vel_SparksEmitter.push(new THREE.Vector3(0, 0, 0));
                this.sz_SparksEmitter.push(0);
                this.rot_SparksEmitter.push(0);
            }
        } else {
            mesh_SparksEmitter = this.mesh_SparksEmitter;
            mesh_SparksEmitter.visible = true;
            geo_SparksEmitter = this.geo_SparksEmitter!;
            frm_SparksEmitter = mesh_SparksEmitter.geometry.getAttribute("aFrame").array as Float32Array;
            opc_SparksEmitter = mesh_SparksEmitter.geometry.getAttribute("aOpacity").array as Float32Array;
            clr_SparksEmitter = mesh_SparksEmitter.geometry.getAttribute("aColor").array as Float32Array;
            vel_buf_SparksEmitter = mesh_SparksEmitter.geometry.getAttribute("aVelocity").array as Float32Array;
            off_buf_SparksEmitter = mesh_SparksEmitter.geometry.getAttribute("aOffset").array as Float32Array;
        }

        // Reset particle arrays in place
        for (let i = 0; i < cnt_SparksEmitter; i++) {
            this.life_SparksEmitter[i] = 1.0;
            this.maxLife_SparksEmitter[i] = 1.0;
            this.pos_SparksEmitter[i].set(x, y, z);
            this.vel_SparksEmitter[i].set(0, 0, 0);
            this.sz_SparksEmitter[i] = 0;
            this.rot_SparksEmitter[i] = 0;
        }

        this.ptr_SparksEmitter = 0;
        this.spawnTimer_SparksEmitter = 0;

        const spawnParticle_SparksEmitter = (i: number) => {
            this.life_SparksEmitter[i] = 0;
            this.maxLife_SparksEmitter[i] = rng(0.25, 0.35);
            this.sz_SparksEmitter[i] = rng(0.07, 0.07);
            this.rot_SparksEmitter[i] = rng(0, Math.PI * 2);

            const theta = Math.random() * Math.PI * 2;
            const phi = Math.acos(rng(-1, 1));
            const speed = rng(12, 28) * 2.0;
            const srad = 0.25 * 2.0;
            this.pos_SparksEmitter[i].set(
                x + Math.sin(phi) * Math.cos(theta) * srad,
                y + Math.sin(phi) * Math.sin(theta) * srad,
                z + Math.cos(phi) * srad,
            );
            this.vel_SparksEmitter[i].set(
                Math.sin(phi) * Math.cos(theta) * speed,
                Math.sin(phi) * Math.sin(theta) * speed,
                Math.cos(phi) * speed,
            );
        };

        // Trigger initial bursts
        const initialBurst_SparksEmitter = 0;
        for (
            let i = 0;
            i < Math.min(cnt_SparksEmitter, initialBurst_SparksEmitter);
            i++
        ) {
            spawnParticle_SparksEmitter(this.ptr_SparksEmitter);
            this.ptr_SparksEmitter = (this.ptr_SparksEmitter + 1) % cnt_SparksEmitter;
        }

        const colorKeys_SparksEmitter: ColorKey[] | null = [
            { value: { r: 1.0, g: 1.0, b: 1.0 }, pos: 0.0 },
            { value: { r: 1.0, g: 1.0, b: 1.0 }, pos: 1.0 },
        ];
        const alphaKeys_SparksEmitter: AlphaKey[] | null = [
            { value: 0.0, pos: 0.0 },
            { value: 1.0, pos: 0.22353 },
            { value: 1.0, pos: 0.83487 },
            { value: 0.0, pos: 1.0 },
        ];

        // Update closure captured for this emitter
        const update_SparksEmitter = (dt: number) => {
            // Spawn particles continuously over time
            const rate = 0;
            if (rate > 0) {
                this.spawnTimer_SparksEmitter += dt;
                const interval = 1.0 / rate;
                while (this.spawnTimer_SparksEmitter >= interval) {
                    spawnParticle_SparksEmitter(this.ptr_SparksEmitter);
                    this.ptr_SparksEmitter =
                        (this.ptr_SparksEmitter + 1) % cnt_SparksEmitter;
                    this.spawnTimer_SparksEmitter -= interval;
                }
            }

            for (let i = 0; i < cnt_SparksEmitter; i++) {
                if (this.life_SparksEmitter[i] >= this.maxLife_SparksEmitter[i]) {
                    mesh_SparksEmitter.setMatrixAt(i, hideM);
                    opc_SparksEmitter[i] = 0;
                    continue;
                }
                this.life_SparksEmitter[i] += dt;
                const pct = Math.min(
                    1,
                    this.life_SparksEmitter[i] / this.maxLife_SparksEmitter[i],
                );
                if (this.life_SparksEmitter[i] >= this.maxLife_SparksEmitter[i]) {
                    mesh_SparksEmitter.setMatrixAt(i, hideM);
                    opc_SparksEmitter[i] = 0;
                    continue;
                }
                // Physics: gravity + drag
                this.vel_SparksEmitter[i].y += -19.6 * dt;

                const speed_SparksEmitter = this.vel_SparksEmitter[i].length();
                const limit_SparksEmitter = 1 * 2.0;
                if (speed_SparksEmitter > limit_SparksEmitter) {
                    const percent =
                        (speed_SparksEmitter - limit_SparksEmitter) /
                        speed_SparksEmitter;
                    this.vel_SparksEmitter[i].multiplyScalar(
                        Math.max(0, 1 - percent * 0.2 * dt * 20),
                    );
                }

                this.pos_SparksEmitter[i].addScaledVector(this.vel_SparksEmitter[i], dt);

                const sizeBez: PiecewiseCurve[] = [
                    {
                        start: 0,
                        end: 1,
                        p0: 1,
                        p1: 1,
                        p2: 0.6666666666666666,
                        p3: 0,
                    },
                ];
                const scaledSz =
                    this.sz_SparksEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

                const alpha = alphaKeys_SparksEmitter
                    ? evalAlpha(alphaKeys_SparksEmitter, pct)
                    : 1 - pct;
                const col = colorKeys_SparksEmitter
                    ? evalColor(colorKeys_SparksEmitter, pct)
                    : { r: 1, g: 1, b: 1 };

                T.position.set(0, 0, 0);
                T.quaternion.set(0, 0, 0, 1);

                // StretchedBillboard: shader handles orientation via aVelocity/aOffset
                T.scale.setScalar(scaledSz);
                off_buf_SparksEmitter[i * 3 + 0] = this.pos_SparksEmitter[i].x;
                off_buf_SparksEmitter[i * 3 + 1] = this.pos_SparksEmitter[i].y;
                off_buf_SparksEmitter[i * 3 + 2] = this.pos_SparksEmitter[i].z;
                vel_buf_SparksEmitter[i * 3 + 0] =
                    this.vel_SparksEmitter[i].x * 0.01;
                vel_buf_SparksEmitter[i * 3 + 1] =
                    this.vel_SparksEmitter[i].y * 0.01;
                vel_buf_SparksEmitter[i * 3 + 2] =
                    this.vel_SparksEmitter[i].z * 0.01;

                T.updateMatrix();
                mesh_SparksEmitter.setMatrixAt(i, T.matrix);

                const frameBez: PiecewiseCurve[] = [];
                const frameRaw = pct * 1;
                frm_SparksEmitter[i] = Math.min(0, Math.floor(frameRaw));
                opc_SparksEmitter[i] = alpha;
                clr_SparksEmitter[i * 3 + 0] = col.r * cfgColor.r;
                clr_SparksEmitter[i * 3 + 1] = col.g * cfgColor.g;
                clr_SparksEmitter[i * 3 + 2] = col.b * cfgColor.b;
                mesh_SparksEmitter.geometry.attributes.aVelocity.needsUpdate = true;
                mesh_SparksEmitter.geometry.attributes.aOffset.needsUpdate = true;
            }
            mesh_SparksEmitter.instanceMatrix.needsUpdate = true;
            (
                mesh_SparksEmitter.geometry.getAttribute(
                    "aFrame",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
            (
                mesh_SparksEmitter.geometry.getAttribute(
                    "aOpacity",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
            (
                mesh_SparksEmitter.geometry.getAttribute(
                    "aColor",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
        };

        cleanups.push(() => {
            mesh_SparksEmitter.visible = false;
        });

        // ══════════════════════════════════════════════════════════
        // Emitter: GlowEmitter  (count=11, life=[0.3, 0.3], speed=[0, 0])
        // Texture: tex_1.png  Grid: 1x1
        // ══════════════════════════════════════════════════════════
        const cnt_GlowEmitter = 3;
        let geo_GlowEmitter: THREE.PlaneGeometry;
        let mesh_GlowEmitter: THREE.InstancedMesh;
        let frm_GlowEmitter: Float32Array;
        let opc_GlowEmitter: Float32Array;
        let clr_GlowEmitter: Float32Array;
        let isFirst_GlowEmitter = false;

        if (!this.mesh_GlowEmitter) {
            isFirst_GlowEmitter = true;
            geo_GlowEmitter = new THREE.PlaneGeometry(1, 1);
            this.geo_GlowEmitter = geo_GlowEmitter;
            if (!this.mat_GlowEmitter) {
                this.mat_GlowEmitter = new THREE.ShaderMaterial({
                    uniforms: { uMap: { value: this.tex1 } },
            vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vUv = uv;
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
            fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
            transparent: true,
            depthWrite: false,
            side: THREE.DoubleSide,
            blending: THREE.AdditiveBlending,
                });
            }
            mesh_GlowEmitter = new THREE.InstancedMesh(
                geo_GlowEmitter,
                this.mat_GlowEmitter,
                cnt_GlowEmitter,
            );
            mesh_GlowEmitter.frustumCulled = false;
            this.scene.add(mesh_GlowEmitter);
            this.mesh_GlowEmitter = mesh_GlowEmitter;

            const frm_arr = new Float32Array(cnt_GlowEmitter);
            const opc_arr = new Float32Array(cnt_GlowEmitter);
            const clr_arr = new Float32Array(cnt_GlowEmitter * 3);
            mesh_GlowEmitter.geometry.setAttribute("aFrame", new THREE.InstancedBufferAttribute(frm_arr, 1));
            mesh_GlowEmitter.geometry.setAttribute("aOpacity", new THREE.InstancedBufferAttribute(opc_arr, 1));
            mesh_GlowEmitter.geometry.setAttribute("aColor", new THREE.InstancedBufferAttribute(clr_arr, 3));
            frm_GlowEmitter = frm_arr;
            opc_GlowEmitter = opc_arr;
            clr_GlowEmitter = clr_arr;
            for (let i = 0; i < cnt_GlowEmitter; i++) {
                this.life_GlowEmitter.push(1.0);
                this.maxLife_GlowEmitter.push(1.0);
                this.pos_GlowEmitter.push(new THREE.Vector3(x, y, z));
                this.vel_GlowEmitter.push(new THREE.Vector3(0, 0, 0));
                this.sz_GlowEmitter.push(0);
                this.rot_GlowEmitter.push(0);
            }
        } else {
            mesh_GlowEmitter = this.mesh_GlowEmitter;
            mesh_GlowEmitter.visible = true;
            geo_GlowEmitter = this.geo_GlowEmitter!;
            frm_GlowEmitter = mesh_GlowEmitter.geometry.getAttribute("aFrame").array as Float32Array;
            opc_GlowEmitter = mesh_GlowEmitter.geometry.getAttribute("aOpacity").array as Float32Array;
            clr_GlowEmitter = mesh_GlowEmitter.geometry.getAttribute("aColor").array as Float32Array;
        }

        // Reset particle arrays in place
        for (let i = 0; i < cnt_GlowEmitter; i++) {
            this.life_GlowEmitter[i] = 1.0;
            this.maxLife_GlowEmitter[i] = 1.0;
            this.pos_GlowEmitter[i].set(x, y, z);
            this.vel_GlowEmitter[i].set(0, 0, 0);
            this.sz_GlowEmitter[i] = 0;
            this.rot_GlowEmitter[i] = 0;
        }

        this.ptr_GlowEmitter = 0;
        this.spawnTimer_GlowEmitter = 0;

        const spawnParticle_GlowEmitter = (i: number) => {
            this.life_GlowEmitter[i] = 0;
            this.maxLife_GlowEmitter[i] = rng(0.3, 0.3);
            this.sz_GlowEmitter[i] = rng(5.75, 5.75);
            this.rot_GlowEmitter[i] = rng(0, Math.PI * 2);

            const theta = Math.random() * Math.PI * 2;
            const phi = Math.acos(rng(-1, 1));
            const speed = rng(0, 0) * 2.0;
            const srad = 0 * 2.0;
            this.pos_GlowEmitter[i].set(
                x + Math.sin(phi) * Math.cos(theta) * srad,
                y + Math.sin(phi) * Math.sin(theta) * srad,
                z + Math.cos(phi) * srad,
            );
            this.vel_GlowEmitter[i].set(
                Math.sin(phi) * Math.cos(theta) * speed,
                Math.sin(phi) * Math.sin(theta) * speed,
                Math.cos(phi) * speed,
            );
        };

        // Trigger initial bursts
        const initialBurst_GlowEmitter = 1;
        for (
            let i = 0;
            i < Math.min(cnt_GlowEmitter, initialBurst_GlowEmitter);
            i++
        ) {
            spawnParticle_GlowEmitter(this.ptr_GlowEmitter);
            this.ptr_GlowEmitter = (this.ptr_GlowEmitter + 1) % cnt_GlowEmitter;
        }

        const colorKeys_GlowEmitter: ColorKey[] | null = [
            { value: { r: 0.72941, g: 0.97647, b: 1.0 }, pos: 0.0 },
            { value: { r: 0.0, g: 1.0, b: 1.0 }, pos: 1.0 },
        ];
        const alphaKeys_GlowEmitter: AlphaKey[] | null = [
            { value: 1.0, pos: 0.0 },
            { value: 0.0, pos: 1.0 },
        ];

        // Update closure captured for this emitter
        const update_GlowEmitter = (dt: number) => {
            // Spawn particles continuously over time
            const rate = 0;
            if (rate > 0) {
                this.spawnTimer_GlowEmitter += dt;
                const interval = 1.0 / rate;
                while (this.spawnTimer_GlowEmitter >= interval) {
                    spawnParticle_GlowEmitter(this.ptr_GlowEmitter);
                    this.ptr_GlowEmitter = (this.ptr_GlowEmitter + 1) % cnt_GlowEmitter;
                    this.spawnTimer_GlowEmitter -= interval;
                }
            }

            for (let i = 0; i < cnt_GlowEmitter; i++) {
                if (this.life_GlowEmitter[i] >= this.maxLife_GlowEmitter[i]) {
                    mesh_GlowEmitter.setMatrixAt(i, hideM);

                    continue;
                }
                this.life_GlowEmitter[i] += dt;
                const pct = Math.min(
                    1,
                    this.life_GlowEmitter[i] / this.maxLife_GlowEmitter[i],
                );
                if (this.life_GlowEmitter[i] >= this.maxLife_GlowEmitter[i]) {
                    mesh_GlowEmitter.setMatrixAt(i, hideM);

                    continue;
                }
                // Physics: gravity + drag
                this.vel_GlowEmitter[i].y += 0 * dt;

                const speed_GlowEmitter = this.vel_GlowEmitter[i].length();
                const limit_GlowEmitter = 0.7 * 2.0;
                if (speed_GlowEmitter > limit_GlowEmitter) {
                    const percent =
                        (speed_GlowEmitter - limit_GlowEmitter) /
                        speed_GlowEmitter;
                    this.vel_GlowEmitter[i].multiplyScalar(
                        Math.max(0, 1 - percent * 0.09 * dt * 20),
                    );
                }

                this.pos_GlowEmitter[i].addScaledVector(this.vel_GlowEmitter[i], dt);

                const sizeBez: PiecewiseCurve[] = [
                    {
                        start: 0,
                        end: 1,
                        p0: 1,
                        p1: 1,
                        p2: 0.89311555,
                        p3: 0.61313975,
                    },
                ];
                const scaledSz =
                    this.sz_GlowEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

                const alpha = alphaKeys_GlowEmitter
                    ? evalAlpha(alphaKeys_GlowEmitter, pct)
                    : 1 - pct;
                const col = colorKeys_GlowEmitter
                    ? evalColor(colorKeys_GlowEmitter, pct)
                    : { r: 1, g: 1, b: 1 };

                T.position.set(0, 0, 0);
                T.quaternion.set(0, 0, 0, 1);

                T.position.copy(this.pos_GlowEmitter[i]);

                T.quaternion.copy(cq);
                T.rotateZ(this.rot_GlowEmitter[i]);

                T.scale.setScalar(scaledSz);

                T.updateMatrix();
                mesh_GlowEmitter.setMatrixAt(i, T.matrix);

                const frameBez: PiecewiseCurve[] = [];
                const frameRaw = pct * 1;
                frm_GlowEmitter[i] = Math.min(0, Math.floor(frameRaw));
                opc_GlowEmitter[i] = alpha;
                clr_GlowEmitter[i * 3 + 0] = col.r * cfgColor.r;
                clr_GlowEmitter[i * 3 + 1] = col.g * cfgColor.g;
                clr_GlowEmitter[i * 3 + 2] = col.b * cfgColor.b;
            }
            mesh_GlowEmitter.instanceMatrix.needsUpdate = true;
            (
                mesh_GlowEmitter.geometry.getAttribute(
                    "aFrame",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
            (
                mesh_GlowEmitter.geometry.getAttribute(
                    "aOpacity",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
            (
                mesh_GlowEmitter.geometry.getAttribute(
                    "aColor",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
        };

        cleanups.push(() => {
            mesh_GlowEmitter.visible = false;
        });

        // ══════════════════════════════════════════════════════════
        // Emitter: CloudBurstEmitter  (count=24, life=[0.6, 0.7], speed=[1, 8])
        // Texture: tex_2.png  Grid: 2x2
        // ══════════════════════════════════════════════════════════
        const cnt_CloudBurstEmitter = 0;
        let geo_CloudBurstEmitter: THREE.PlaneGeometry;
        let mesh_CloudBurstEmitter: THREE.InstancedMesh;
        let frm_CloudBurstEmitter: Float32Array;
        let opc_CloudBurstEmitter: Float32Array;
        let clr_CloudBurstEmitter: Float32Array;
        let isFirst_CloudBurstEmitter = false;

        if (!this.mesh_CloudBurstEmitter) {
            isFirst_CloudBurstEmitter = true;
            geo_CloudBurstEmitter = new THREE.PlaneGeometry(1, 1);
            this.geo_CloudBurstEmitter = geo_CloudBurstEmitter;
            if (!this.mat_CloudBurstEmitter) {
                this.mat_CloudBurstEmitter = new THREE.ShaderMaterial({
                    uniforms: { uMap: { value: this.tex2 } },
            vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          float c = mod(aFrame, 2.0); float r = floor(aFrame / 2.0);
          vUv = vec2((c + uv.x) / 2.0, 1.0 - (r + 1.0 - uv.y) / 2.0);
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
            fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
            transparent: true,
            depthWrite: false,
            side: THREE.DoubleSide,
            blending: THREE.AdditiveBlending,
                });
            }
            mesh_CloudBurstEmitter = new THREE.InstancedMesh(
                geo_CloudBurstEmitter,
                this.mat_CloudBurstEmitter,
                cnt_CloudBurstEmitter,
            );
            mesh_CloudBurstEmitter.frustumCulled = false;
            this.scene.add(mesh_CloudBurstEmitter);
            this.mesh_CloudBurstEmitter = mesh_CloudBurstEmitter;

            const frm_arr = new Float32Array(cnt_CloudBurstEmitter);
            const opc_arr = new Float32Array(cnt_CloudBurstEmitter);
            const clr_arr = new Float32Array(cnt_CloudBurstEmitter * 3);
            mesh_CloudBurstEmitter.geometry.setAttribute("aFrame", new THREE.InstancedBufferAttribute(frm_arr, 1));
            mesh_CloudBurstEmitter.geometry.setAttribute("aOpacity", new THREE.InstancedBufferAttribute(opc_arr, 1));
            mesh_CloudBurstEmitter.geometry.setAttribute("aColor", new THREE.InstancedBufferAttribute(clr_arr, 3));
            frm_CloudBurstEmitter = frm_arr;
            opc_CloudBurstEmitter = opc_arr;
            clr_CloudBurstEmitter = clr_arr;
            for (let i = 0; i < cnt_CloudBurstEmitter; i++) {
                this.life_CloudBurstEmitter.push(1.0);
                this.maxLife_CloudBurstEmitter.push(1.0);
                this.pos_CloudBurstEmitter.push(new THREE.Vector3(x, y, z));
                this.vel_CloudBurstEmitter.push(new THREE.Vector3(0, 0, 0));
                this.sz_CloudBurstEmitter.push(0);
                this.rot_CloudBurstEmitter.push(0);
            }
        } else {
            mesh_CloudBurstEmitter = this.mesh_CloudBurstEmitter;
            mesh_CloudBurstEmitter.visible = true;
            geo_CloudBurstEmitter = this.geo_CloudBurstEmitter!;
            frm_CloudBurstEmitter = mesh_CloudBurstEmitter.geometry.getAttribute("aFrame").array as Float32Array;
            opc_CloudBurstEmitter = mesh_CloudBurstEmitter.geometry.getAttribute("aOpacity").array as Float32Array;
            clr_CloudBurstEmitter = mesh_CloudBurstEmitter.geometry.getAttribute("aColor").array as Float32Array;
        }

        // Reset particle arrays in place
        for (let i = 0; i < cnt_CloudBurstEmitter; i++) {
            this.life_CloudBurstEmitter[i] = 1.0;
            this.maxLife_CloudBurstEmitter[i] = 1.0;
            this.pos_CloudBurstEmitter[i].set(x, y, z);
            this.vel_CloudBurstEmitter[i].set(0, 0, 0);
            this.sz_CloudBurstEmitter[i] = 0;
            this.rot_CloudBurstEmitter[i] = 0;
        }

        this.ptr_CloudBurstEmitter = 0;
        this.spawnTimer_CloudBurstEmitter = 0;

        const spawnParticle_CloudBurstEmitter = (i: number) => {
            this.life_CloudBurstEmitter[i] = 0;
            this.maxLife_CloudBurstEmitter[i] = rng(0.6, 0.7);
            this.sz_CloudBurstEmitter[i] = rng(0.9, 1.2);
            this.rot_CloudBurstEmitter[i] = rng(0, Math.PI * 2);

            const theta = Math.random() * Math.PI * 2;
            const phi = Math.acos(rng(-1, 1));
            const speed = rng(1, 8) * 2.0;
            const srad = 0.2 * 2.0;
            this.pos_CloudBurstEmitter[i].set(
                x + Math.sin(phi) * Math.cos(theta) * srad,
                y + Math.sin(phi) * Math.sin(theta) * srad,
                z + Math.cos(phi) * srad,
            );
            this.vel_CloudBurstEmitter[i].set(
                Math.sin(phi) * Math.cos(theta) * speed,
                Math.sin(phi) * Math.sin(theta) * speed,
                Math.cos(phi) * speed,
            );
        };

        // Trigger initial bursts
        const initialBurst_CloudBurstEmitter = 0;
        for (
            let i = 0;
            i < Math.min(cnt_CloudBurstEmitter, initialBurst_CloudBurstEmitter);
            i++
        ) {
            spawnParticle_CloudBurstEmitter(this.ptr_CloudBurstEmitter);
            this.ptr_CloudBurstEmitter =
                (this.ptr_CloudBurstEmitter + 1) % cnt_CloudBurstEmitter;
        }

        const colorKeys_CloudBurstEmitter: ColorKey[] | null = [
            { value: { r: 0.0, g: 0.37647, b: 0.56471 }, pos: 0.0 },
            { value: { r: 0.17647, g: 0.18039, b: 0.23529 }, pos: 1.0 },
        ];
        const alphaKeys_CloudBurstEmitter: AlphaKey[] | null = [
            { value: 1.0, pos: 0.0 },
            { value: 1.0, pos: 0.90001 },
            { value: 0.0, pos: 1.0 },
        ];

        // Update closure captured for this emitter
        const update_CloudBurstEmitter = (dt: number) => {
            // Spawn particles continuously over time
            const rate = 0;
            if (rate > 0) {
                this.spawnTimer_CloudBurstEmitter += dt;
                const interval = 1.0 / rate;
                while (this.spawnTimer_CloudBurstEmitter >= interval) {
                    spawnParticle_CloudBurstEmitter(this.ptr_CloudBurstEmitter);
                    this.ptr_CloudBurstEmitter =
                        (this.ptr_CloudBurstEmitter + 1) % cnt_CloudBurstEmitter;
                    this.spawnTimer_CloudBurstEmitter -= interval;
                }
            }

            for (let i = 0; i < cnt_CloudBurstEmitter; i++) {
                if (this.life_CloudBurstEmitter[i] >= this.maxLife_CloudBurstEmitter[i]) {
                    mesh_CloudBurstEmitter.setMatrixAt(i, hideM);
                    opc_CloudBurstEmitter[i] = 0;
                    continue;
                }
                this.life_CloudBurstEmitter[i] += dt;
                const pct = Math.min(
                    1,
                    this.life_CloudBurstEmitter[i] / this.maxLife_CloudBurstEmitter[i],
                );
                if (this.life_CloudBurstEmitter[i] >= this.maxLife_CloudBurstEmitter[i]) {
                    mesh_CloudBurstEmitter.setMatrixAt(i, hideM);
                    opc_CloudBurstEmitter[i] = 0;
                    continue;
                }
                // Physics: gravity + drag
                this.vel_CloudBurstEmitter[i].y += 0 * dt;

                const speed_CloudBurstEmitter =
                    this.vel_CloudBurstEmitter[i].length();
                const limit_CloudBurstEmitter = 0.5 * 2.0;
                if (speed_CloudBurstEmitter > limit_CloudBurstEmitter) {
                    const percent =
                        (speed_CloudBurstEmitter - limit_CloudBurstEmitter) /
                        speed_CloudBurstEmitter;
                    this.vel_CloudBurstEmitter[i].multiplyScalar(
                        Math.max(0, 1 - percent * 0.2 * dt * 20),
                    );
                }

                this.pos_CloudBurstEmitter[i].addScaledVector(
                    this.vel_CloudBurstEmitter[i],
                    dt,
                );

                const rotSpeedBez_CloudBurstEmitter: PiecewiseCurve[] = [
                    { start: 0, end: 1, p0: 1, p1: 1, p2: 0, p3: 0 },
                ];
                this.rot_CloudBurstEmitter[i] +=
                    evalPiecewise(rotSpeedBez_CloudBurstEmitter, pct) * dt;

                const sizeBez: PiecewiseCurve[] = [
                    {
                        start: 0,
                        end: 1,
                        p0: 1,
                        p1: 1,
                        p2: 0.6666666666666666,
                        p3: 0,
                    },
                ];
                const scaledSz =
                    this.sz_CloudBurstEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

                const alpha = alphaKeys_CloudBurstEmitter
                    ? evalAlpha(alphaKeys_CloudBurstEmitter, pct)
                    : 1 - pct;
                const col = colorKeys_CloudBurstEmitter
                    ? evalColor(colorKeys_CloudBurstEmitter, pct)
                    : { r: 1, g: 1, b: 1 };

                T.position.set(0, 0, 0);
                T.quaternion.set(0, 0, 0, 1);

                T.position.copy(this.pos_CloudBurstEmitter[i]);

                T.quaternion.copy(cq);
                T.rotateZ(this.rot_CloudBurstEmitter[i]);

                T.scale.setScalar(scaledSz);

                T.updateMatrix();
                mesh_CloudBurstEmitter.setMatrixAt(i, T.matrix);

                const frameBez: PiecewiseCurve[] = [
                    {
                        start: 0,
                        end: 1.0,
                        p0: 0,
                        p1: 0,
                        p2: 3.9996,
                        p3: 3.9996,
                    },
                ];
                const frameRaw = evalPiecewise(frameBez, pct);
                frm_CloudBurstEmitter[i] = Math.min(3, Math.floor(frameRaw));
                opc_CloudBurstEmitter[i] = alpha;
                clr_CloudBurstEmitter[i * 3 + 0] = col.r * cfgColor.r;
                clr_CloudBurstEmitter[i * 3 + 1] = col.g * cfgColor.g;
                clr_CloudBurstEmitter[i * 3 + 2] = col.b * cfgColor.b;
            }
            mesh_CloudBurstEmitter.instanceMatrix.needsUpdate = true;
            (
                mesh_CloudBurstEmitter.geometry.getAttribute(
                    "aFrame",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
            (
                mesh_CloudBurstEmitter.geometry.getAttribute(
                    "aOpacity",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
            (
                mesh_CloudBurstEmitter.geometry.getAttribute(
                    "aColor",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
        };

        cleanups.push(() => {
            mesh_CloudBurstEmitter.visible = false;
        });

        // ══════════════════════════════════════════════════════════
        // Emitter: TrailEmitter  (count=300, life=[0.25, 0.6], speed=[0, 0])
        // Texture: tex_2.png  Grid: 2x2
        // ══════════════════════════════════════════════════════════
        const cnt_TrailEmitter = 0;
        let geo_TrailEmitter: THREE.PlaneGeometry;
        let mesh_TrailEmitter: THREE.InstancedMesh;
        let frm_TrailEmitter: Float32Array;
        let opc_TrailEmitter: Float32Array;
        let clr_TrailEmitter: Float32Array;
        let isFirst_TrailEmitter = false;

        if (!this.mesh_TrailEmitter) {
            isFirst_TrailEmitter = true;
            geo_TrailEmitter = new THREE.PlaneGeometry(1, 1);
            this.geo_TrailEmitter = geo_TrailEmitter;
            if (!this.mat_TrailEmitter) {
                this.mat_TrailEmitter = new THREE.ShaderMaterial({
                    uniforms: { uMap: { value: this.tex2 } },
            vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          float c = mod(aFrame, 2.0); float r = floor(aFrame / 2.0);
          vUv = vec2((c + uv.x) / 2.0, 1.0 - (r + 1.0 - uv.y) / 2.0);
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
            fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
            transparent: true,
            depthWrite: false,
            side: THREE.DoubleSide,
            blending: THREE.AdditiveBlending,
                });
            }
            mesh_TrailEmitter = new THREE.InstancedMesh(
                geo_TrailEmitter,
                this.mat_TrailEmitter,
                cnt_TrailEmitter,
            );
            mesh_TrailEmitter.frustumCulled = false;
            this.scene.add(mesh_TrailEmitter);
            this.mesh_TrailEmitter = mesh_TrailEmitter;

            const frm_arr = new Float32Array(cnt_TrailEmitter);
            const opc_arr = new Float32Array(cnt_TrailEmitter);
            const clr_arr = new Float32Array(cnt_TrailEmitter * 3);
            mesh_TrailEmitter.geometry.setAttribute("aFrame", new THREE.InstancedBufferAttribute(frm_arr, 1));
            mesh_TrailEmitter.geometry.setAttribute("aOpacity", new THREE.InstancedBufferAttribute(opc_arr, 1));
            mesh_TrailEmitter.geometry.setAttribute("aColor", new THREE.InstancedBufferAttribute(clr_arr, 3));
            frm_TrailEmitter = frm_arr;
            opc_TrailEmitter = opc_arr;
            clr_TrailEmitter = clr_arr;
            for (let i = 0; i < cnt_TrailEmitter; i++) {
                this.life_TrailEmitter.push(1.0);
                this.maxLife_TrailEmitter.push(1.0);
                this.pos_TrailEmitter.push(new THREE.Vector3(x, y, z));
                this.vel_TrailEmitter.push(new THREE.Vector3(0, 0, 0));
                this.sz_TrailEmitter.push(0);
                this.rot_TrailEmitter.push(0);
            }
        } else {
            mesh_TrailEmitter = this.mesh_TrailEmitter;
            mesh_TrailEmitter.visible = true;
            geo_TrailEmitter = this.geo_TrailEmitter!;
            frm_TrailEmitter = mesh_TrailEmitter.geometry.getAttribute("aFrame").array as Float32Array;
            opc_TrailEmitter = mesh_TrailEmitter.geometry.getAttribute("aOpacity").array as Float32Array;
            clr_TrailEmitter = mesh_TrailEmitter.geometry.getAttribute("aColor").array as Float32Array;
        }

        // Reset particle arrays in place
        for (let i = 0; i < cnt_TrailEmitter; i++) {
            this.life_TrailEmitter[i] = 1.0;
            this.maxLife_TrailEmitter[i] = 1.0;
            this.pos_TrailEmitter[i].set(x, y, z);
            this.vel_TrailEmitter[i].set(0, 0, 0);
            this.sz_TrailEmitter[i] = 0;
            this.rot_TrailEmitter[i] = 0;
        }

        this.ptr_TrailEmitter = 0;
        this.spawnTimer_TrailEmitter = 0;

        const spawnParticle_TrailEmitter = (i: number) => {
            this.life_TrailEmitter[i] = 0;
            this.maxLife_TrailEmitter[i] = rng(0.25, 0.6);
            this.sz_TrailEmitter[i] = rng(1, 0.56875);
            this.rot_TrailEmitter[i] = rng(0, Math.PI * 2);

            const theta = Math.random() * Math.PI * 2;
            const phi = Math.acos(rng(-1, 1));
            const speed = rng(0, 0) * 2.0;
            const srad = 0 * 2.0;
            this.pos_TrailEmitter[i].set(
                x + Math.sin(phi) * Math.cos(theta) * srad,
                y + Math.sin(phi) * Math.sin(theta) * srad,
                z + Math.cos(phi) * srad,
            );
            this.vel_TrailEmitter[i].set(
                Math.sin(phi) * Math.cos(theta) * speed,
                Math.sin(phi) * Math.sin(theta) * speed,
                Math.cos(phi) * speed,
            );
        };

        // Trigger initial bursts
        const initialBurst_TrailEmitter = 0;
        for (
            let i = 0;
            i < Math.min(cnt_TrailEmitter, initialBurst_TrailEmitter);
            i++
        ) {
            spawnParticle_TrailEmitter(this.ptr_TrailEmitter);
            this.ptr_TrailEmitter = (this.ptr_TrailEmitter + 1) % cnt_TrailEmitter;
        }

        const colorKeys_TrailEmitter: ColorKey[] | null = [
            { value: { r: 0.0, g: 0.37647, b: 0.56471 }, pos: 0.0 },
            { value: { r: 0.17647, g: 0.18039, b: 0.23529 }, pos: 1.0 },
        ];
        const alphaKeys_TrailEmitter: AlphaKey[] | null = [
            { value: 1.0, pos: 0.0 },
            { value: 1.0, pos: 0.90001 },
            { value: 0.0, pos: 1.0 },
        ];

        // Update closure captured for this emitter
        const update_TrailEmitter = (dt: number) => {
            // Spawn particles continuously over time
            const rate = 0;
            if (rate > 0) {
                this.spawnTimer_TrailEmitter += dt;
                const interval = 1.0 / rate;
                while (this.spawnTimer_TrailEmitter >= interval) {
                    spawnParticle_TrailEmitter(this.ptr_TrailEmitter);
                    this.ptr_TrailEmitter =
                        (this.ptr_TrailEmitter + 1) % cnt_TrailEmitter;
                    this.spawnTimer_TrailEmitter -= interval;
                }
            }

            for (let i = 0; i < cnt_TrailEmitter; i++) {
                if (this.life_TrailEmitter[i] >= this.maxLife_TrailEmitter[i]) {
                    mesh_TrailEmitter.setMatrixAt(i, hideM);
                    opc_TrailEmitter[i] = 0;
                    continue;
                }
                this.life_TrailEmitter[i] += dt;
                const pct = Math.min(
                    1,
                    this.life_TrailEmitter[i] / this.maxLife_TrailEmitter[i],
                );
                if (this.life_TrailEmitter[i] >= this.maxLife_TrailEmitter[i]) {
                    mesh_TrailEmitter.setMatrixAt(i, hideM);
                    opc_TrailEmitter[i] = 0;
                    continue;
                }
                // Physics: gravity + drag
                this.vel_TrailEmitter[i].y += 1.9600000000000002 * dt;

                const speed_TrailEmitter = this.vel_TrailEmitter[i].length();
                const limit_TrailEmitter = 0 * 2.0;
                if (speed_TrailEmitter > limit_TrailEmitter) {
                    const percent =
                        (speed_TrailEmitter - limit_TrailEmitter) /
                        speed_TrailEmitter;
                    this.vel_TrailEmitter[i].multiplyScalar(
                        Math.max(0, 1 - percent * 0.05 * dt * 20),
                    );
                }

                this.pos_TrailEmitter[i].addScaledVector(this.vel_TrailEmitter[i], dt);

                const rotSpeedBez_TrailEmitter: PiecewiseCurve[] = [
                    {
                        start: 0,
                        end: 1,
                        p0: 1,
                        p1: 1,
                        p2: 0.4065934,
                        p3: 0.4065934,
                    },
                ];
                this.rot_TrailEmitter[i] +=
                    evalPiecewise(rotSpeedBez_TrailEmitter, pct) * dt;

                const sizeBez: PiecewiseCurve[] = [
                    {
                        start: 0,
                        end: 0.21464643,
                        p0: 0.27548078,
                        p1: 0.27548078,
                        p2: 0.7724670801145349,
                        p3: 0.77080387,
                    },
                    {
                        start: 0.21464643,
                        end: 1,
                        p0: 0.77080387,
                        p1: 0.7647184764478682,
                        p2: 0.6540969042768533,
                        p3: 0,
                    },
                ];
                const scaledSz =
                    this.sz_TrailEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

                const alpha = alphaKeys_TrailEmitter
                    ? evalAlpha(alphaKeys_TrailEmitter, pct)
                    : 1 - pct;
                const col = colorKeys_TrailEmitter
                    ? evalColor(colorKeys_TrailEmitter, pct)
                    : { r: 1, g: 1, b: 1 };

                T.position.set(0, 0, 0);
                T.quaternion.set(0, 0, 0, 1);

                T.position.copy(this.pos_TrailEmitter[i]);

                T.quaternion.copy(cq);
                T.rotateZ(this.rot_TrailEmitter[i]);

                T.scale.setScalar(scaledSz);

                T.updateMatrix();
                mesh_TrailEmitter.setMatrixAt(i, T.matrix);

                const frameBez: PiecewiseCurve[] = [
                    {
                        start: 0,
                        end: 1.0,
                        p0: 0,
                        p1: 0,
                        p2: 3.9996,
                        p3: 3.9996,
                    },
                ];
                const frameRaw = evalPiecewise(frameBez, pct);
                frm_TrailEmitter[i] = Math.min(3, Math.floor(frameRaw));
                opc_TrailEmitter[i] = alpha;
                clr_TrailEmitter[i * 3 + 0] = col.r * cfgColor.r;
                clr_TrailEmitter[i * 3 + 1] = col.g * cfgColor.g;
                clr_TrailEmitter[i * 3 + 2] = col.b * cfgColor.b;
            }
            mesh_TrailEmitter.instanceMatrix.needsUpdate = true;
            (
                mesh_TrailEmitter.geometry.getAttribute(
                    "aFrame",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
            (
                mesh_TrailEmitter.geometry.getAttribute(
                    "aOpacity",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
            (
                mesh_TrailEmitter.geometry.getAttribute(
                    "aColor",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
        };

        cleanups.push(() => {
            mesh_TrailEmitter.visible = false;
        });

        // ══════════════════════════════════════════════════════════
        // Emitter: SmokeTrailEmitter  (count=17, life=[0.3, 0.55], speed=[25, 40])
        // Texture: tex_0.png  Grid: 1x1
        // ══════════════════════════════════════════════════════════
        const cnt_SmokeTrailEmitter = 0;
        let geo_SmokeTrailEmitter: THREE.PlaneGeometry;
        let mesh_SmokeTrailEmitter: THREE.InstancedMesh;
        let frm_SmokeTrailEmitter: Float32Array;
        let opc_SmokeTrailEmitter: Float32Array;
        let clr_SmokeTrailEmitter: Float32Array;
        let isFirst_SmokeTrailEmitter = false;

        if (!this.mesh_SmokeTrailEmitter) {
            isFirst_SmokeTrailEmitter = true;
            geo_SmokeTrailEmitter = new THREE.PlaneGeometry(1, 1);
            this.geo_SmokeTrailEmitter = geo_SmokeTrailEmitter;
            if (!this.mat_SmokeTrailEmitter) {
                this.mat_SmokeTrailEmitter = new THREE.ShaderMaterial({
                    uniforms: { uMap: { value: this.tex0 } },
            vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vUv = uv;
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
            fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
            transparent: true,
            depthWrite: false,
            side: THREE.DoubleSide,
            blending: THREE.AdditiveBlending,
                });
            }
            mesh_SmokeTrailEmitter = new THREE.InstancedMesh(
                geo_SmokeTrailEmitter,
                this.mat_SmokeTrailEmitter,
                cnt_SmokeTrailEmitter,
            );
            mesh_SmokeTrailEmitter.frustumCulled = false;
            this.scene.add(mesh_SmokeTrailEmitter);
            this.mesh_SmokeTrailEmitter = mesh_SmokeTrailEmitter;

            const frm_arr = new Float32Array(cnt_SmokeTrailEmitter);
            const opc_arr = new Float32Array(cnt_SmokeTrailEmitter);
            const clr_arr = new Float32Array(cnt_SmokeTrailEmitter * 3);
            mesh_SmokeTrailEmitter.geometry.setAttribute("aFrame", new THREE.InstancedBufferAttribute(frm_arr, 1));
            mesh_SmokeTrailEmitter.geometry.setAttribute("aOpacity", new THREE.InstancedBufferAttribute(opc_arr, 1));
            mesh_SmokeTrailEmitter.geometry.setAttribute("aColor", new THREE.InstancedBufferAttribute(clr_arr, 3));
            frm_SmokeTrailEmitter = frm_arr;
            opc_SmokeTrailEmitter = opc_arr;
            clr_SmokeTrailEmitter = clr_arr;
            for (let i = 0; i < cnt_SmokeTrailEmitter; i++) {
                this.life_SmokeTrailEmitter.push(1.0);
                this.maxLife_SmokeTrailEmitter.push(1.0);
                this.pos_SmokeTrailEmitter.push(new THREE.Vector3(x, y, z));
                this.vel_SmokeTrailEmitter.push(new THREE.Vector3(0, 0, 0));
                this.sz_SmokeTrailEmitter.push(0);
                this.rot_SmokeTrailEmitter.push(0);
                this.accumulatedDist_SmokeTrailEmitter.push(0);
            }
        } else {
            mesh_SmokeTrailEmitter = this.mesh_SmokeTrailEmitter;
            mesh_SmokeTrailEmitter.visible = true;
            geo_SmokeTrailEmitter = this.geo_SmokeTrailEmitter!;
            frm_SmokeTrailEmitter = mesh_SmokeTrailEmitter.geometry.getAttribute("aFrame").array as Float32Array;
            opc_SmokeTrailEmitter = mesh_SmokeTrailEmitter.geometry.getAttribute("aOpacity").array as Float32Array;
            clr_SmokeTrailEmitter = mesh_SmokeTrailEmitter.geometry.getAttribute("aColor").array as Float32Array;
        }

        // Reset particle arrays in place
        for (let i = 0; i < cnt_SmokeTrailEmitter; i++) {
            this.life_SmokeTrailEmitter[i] = 1.0;
            this.maxLife_SmokeTrailEmitter[i] = 1.0;
            this.pos_SmokeTrailEmitter[i].set(x, y, z);
            this.vel_SmokeTrailEmitter[i].set(0, 0, 0);
            this.sz_SmokeTrailEmitter[i] = 0;
            this.rot_SmokeTrailEmitter[i] = 0;
            this.accumulatedDist_SmokeTrailEmitter[i] = 0;
        }

        this.ptr_SmokeTrailEmitter = 0;
        this.spawnTimer_SmokeTrailEmitter = 0;

        const spawnParticle_SmokeTrailEmitter = (i: number) => {
            this.life_SmokeTrailEmitter[i] = 0;
            this.maxLife_SmokeTrailEmitter[i] = rng(0.3, 0.55);
            this.sz_SmokeTrailEmitter[i] = rng(0.24, 0.27);
            this.rot_SmokeTrailEmitter[i] = rng(0, Math.PI * 2);
            this.accumulatedDist_SmokeTrailEmitter[i] = 0;
            const theta = Math.random() * Math.PI * 2;
            const phi = Math.acos(rng(-1, 1));
            const speed = rng(25, 40) * 2.0;
            const srad = 0.01 * 2.0;
            this.pos_SmokeTrailEmitter[i].set(
                x + Math.sin(phi) * Math.cos(theta) * srad,
                y + Math.sin(phi) * Math.sin(theta) * srad,
                z + Math.cos(phi) * srad,
            );
            this.vel_SmokeTrailEmitter[i].set(
                Math.sin(phi) * Math.cos(theta) * speed,
                Math.sin(phi) * Math.sin(theta) * speed,
                Math.cos(phi) * speed,
            );
        };

        // Trigger initial bursts
        const initialBurst_SmokeTrailEmitter = 0;
        for (
            let i = 0;
            i < Math.min(cnt_SmokeTrailEmitter, initialBurst_SmokeTrailEmitter);
            i++
        ) {
            spawnParticle_SmokeTrailEmitter(this.ptr_SmokeTrailEmitter);
            this.ptr_SmokeTrailEmitter =
                (this.ptr_SmokeTrailEmitter + 1) % cnt_SmokeTrailEmitter;
        }

        const colorKeys_SmokeTrailEmitter: ColorKey[] | null = [
            { value: { r: 1.0, g: 1.0, b: 1.0 }, pos: 0.0 },
            { value: { r: 1.0, g: 1.0, b: 1.0 }, pos: 1.0 },
        ];
        const alphaKeys_SmokeTrailEmitter: AlphaKey[] | null = [
            { value: 1.0, pos: 0.0 },
            { value: 1.0, pos: 0.81186 },
            { value: 0.0, pos: 1.0 },
        ];

        // Update closure captured for this emitter
        const update_SmokeTrailEmitter = (dt: number) => {
            // Spawn particles continuously over time
            const rate = 0;
            if (rate > 0) {
                this.spawnTimer_SmokeTrailEmitter += dt;
                const interval = 1.0 / rate;
                while (this.spawnTimer_SmokeTrailEmitter >= interval) {
                    spawnParticle_SmokeTrailEmitter(this.ptr_SmokeTrailEmitter);
                    this.ptr_SmokeTrailEmitter =
                        (this.ptr_SmokeTrailEmitter + 1) % cnt_SmokeTrailEmitter;
                    this.spawnTimer_SmokeTrailEmitter -= interval;
                }
            }

            for (let i = 0; i < cnt_SmokeTrailEmitter; i++) {
                if (this.life_SmokeTrailEmitter[i] >= this.maxLife_SmokeTrailEmitter[i]) {
                    mesh_SmokeTrailEmitter.setMatrixAt(i, hideM);

                    continue;
                }
                this.life_SmokeTrailEmitter[i] += dt;
                const pct = Math.min(
                    1,
                    this.life_SmokeTrailEmitter[i] / this.maxLife_SmokeTrailEmitter[i],
                );
                if (this.life_SmokeTrailEmitter[i] >= this.maxLife_SmokeTrailEmitter[i]) {
                    mesh_SmokeTrailEmitter.setMatrixAt(i, hideM);

                    continue;
                }
                // Physics: gravity + drag
                this.vel_SmokeTrailEmitter[i].y += -19.6 * dt;

                const speed_SmokeTrailEmitter =
                    this.vel_SmokeTrailEmitter[i].length();
                const limit_SmokeTrailEmitter = 2 * 2.0;
                if (speed_SmokeTrailEmitter > limit_SmokeTrailEmitter) {
                    const percent =
                        (speed_SmokeTrailEmitter - limit_SmokeTrailEmitter) /
                        speed_SmokeTrailEmitter;
                    this.vel_SmokeTrailEmitter[i].multiplyScalar(
                        Math.max(0, 1 - percent * 0.25 * dt * 20),
                    );
                }

                this.pos_SmokeTrailEmitter[i].addScaledVector(
                    this.vel_SmokeTrailEmitter[i],
                    dt,
                );

                const rotSpeedBez_SmokeTrailEmitter: PiecewiseCurve[] = [
                    {
                        start: 0,
                        end: 1,
                        p0: 1,
                        p1: 1,
                        p2: 0.4065934,
                        p3: 0.4065934,
                    },
                ];
                this.rot_SmokeTrailEmitter[i] +=
                    evalPiecewise(rotSpeedBez_SmokeTrailEmitter, pct) * dt;

                const distMoved_SmokeTrailEmitter =
                    this.vel_SmokeTrailEmitter[i].length() * dt;
                this.accumulatedDist_SmokeTrailEmitter[i] +=
                    distMoved_SmokeTrailEmitter;
                const subDist_SmokeTrailEmitter = 5 > 0 ? (1.0 / 5) * 2.0 : 0;
                if (subDist_SmokeTrailEmitter > 0) {
                    while (
                        this.accumulatedDist_SmokeTrailEmitter[i] >=
                        subDist_SmokeTrailEmitter
                    ) {
                        spawnParticle_TrailEmitter(this.ptr_TrailEmitter);
                        this.pos_TrailEmitter[this.ptr_TrailEmitter].copy(
                            this.pos_SmokeTrailEmitter[i],
                        );
                        this.ptr_TrailEmitter =
                            (this.ptr_TrailEmitter + 1) % cnt_TrailEmitter;
                        this.accumulatedDist_SmokeTrailEmitter[i] -=
                            subDist_SmokeTrailEmitter;
                    }
                }

                const sizeBez: PiecewiseCurve[] = [
                    {
                        start: 0,
                        end: 1,
                        p0: 0.7692308,
                        p1: 0.7692308,
                        p2: 0.7843341866666667,
                        p3: 0.46901894,
                    },
                ];
                const scaledSz =
                    this.sz_SmokeTrailEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

                const alpha = alphaKeys_SmokeTrailEmitter
                    ? evalAlpha(alphaKeys_SmokeTrailEmitter, pct)
                    : 1 - pct;
                const col = colorKeys_SmokeTrailEmitter
                    ? evalColor(colorKeys_SmokeTrailEmitter, pct)
                    : { r: 1, g: 1, b: 1 };

                T.position.set(0, 0, 0);
                T.quaternion.set(0, 0, 0, 1);

                T.position.copy(this.pos_SmokeTrailEmitter[i]);

                T.quaternion.copy(cq);
                T.rotateZ(this.rot_SmokeTrailEmitter[i]);

                T.scale.setScalar(scaledSz);

                T.updateMatrix();
                mesh_SmokeTrailEmitter.setMatrixAt(i, T.matrix);

                const frameBez: PiecewiseCurve[] = [];
                const frameRaw = pct * 1;
                frm_SmokeTrailEmitter[i] = Math.min(0, Math.floor(frameRaw));
                opc_SmokeTrailEmitter[i] = alpha;
                clr_SmokeTrailEmitter[i * 3 + 0] = col.r * cfgColor.r;
                clr_SmokeTrailEmitter[i * 3 + 1] = col.g * cfgColor.g;
                clr_SmokeTrailEmitter[i * 3 + 2] = col.b * cfgColor.b;
            }
            mesh_SmokeTrailEmitter.instanceMatrix.needsUpdate = true;
            (
                mesh_SmokeTrailEmitter.geometry.getAttribute(
                    "aFrame",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
            (
                mesh_SmokeTrailEmitter.geometry.getAttribute(
                    "aOpacity",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
            (
                mesh_SmokeTrailEmitter.geometry.getAttribute(
                    "aColor",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
        };

        cleanups.push(() => {
            mesh_SmokeTrailEmitter.visible = false;
        });

        // ══════════════════════════════════════════════════════════
        // Emitter: GasExplosionBlueEmitter  (count=14, life=[0.17, 0.3], speed=[0.1, 0.1])
        // Texture: tex_3.png  Grid: 3x3
        // ══════════════════════════════════════════════════════════
        const cnt_GasExplosionBlueEmitter = 4;
        let geo_GasExplosionBlueEmitter: THREE.PlaneGeometry;
        let mesh_GasExplosionBlueEmitter: THREE.InstancedMesh;
        let frm_GasExplosionBlueEmitter: Float32Array;
        let opc_GasExplosionBlueEmitter: Float32Array;
        let clr_GasExplosionBlueEmitter: Float32Array;
        let vel_buf_GasExplosionBlueEmitter: Float32Array;
        let off_buf_GasExplosionBlueEmitter: Float32Array;
        let isFirst_GasExplosionBlueEmitter = false;

        if (!this.mesh_GasExplosionBlueEmitter) {
            isFirst_GasExplosionBlueEmitter = true;
            geo_GasExplosionBlueEmitter = new THREE.PlaneGeometry(1, 1);
            this.geo_GasExplosionBlueEmitter = geo_GasExplosionBlueEmitter;
            if (!this.mat_GasExplosionBlueEmitter) {
                this.mat_GasExplosionBlueEmitter = new THREE.ShaderMaterial({
                    uniforms: {
                uMap: { value: this.tex3 },
                speedFactor: { value: 1.0 },
            },
            vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor; attribute vec3 aVelocity; attribute vec3 aOffset;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        uniform float speedFactor;
        void main() {
          float c = mod(aFrame, 3.0); float r = floor(aFrame / 3.0);
          vUv = vec2((c + uv.x) / 3.0, 1.0 - (r + 1.0 - uv.y) / 3.0);
          vOpacity = aOpacity; vColor = aColor;
          vec4 mvPos = modelViewMatrix * vec4(aOffset, 1.0);
          vec3 viewVel = normalMatrix * aVelocity;
          float vlength = length(viewVel);
          float avgSize = (instanceMatrix[0][0] + instanceMatrix[1][1]) * 0.5;
          float sz = length(vec3(instanceMatrix[0][0], instanceMatrix[0][1], instanceMatrix[0][2]));
          mvPos.xyz += position.y * normalize(cross(mvPos.xyz, viewVel)) * sz;
          mvPos.xyz -= (position.x + 0.5) * viewVel * (1.0 + 2.5000 / max(vlength, 0.001)) * sz;
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * mvPos;
        }
      `,
            fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
            transparent: true,
            depthWrite: false,
            side: THREE.DoubleSide,
            blending: THREE.NormalBlending,
                });
            }
            mesh_GasExplosionBlueEmitter = new THREE.InstancedMesh(
                geo_GasExplosionBlueEmitter,
                this.mat_GasExplosionBlueEmitter,
                cnt_GasExplosionBlueEmitter,
            );
            mesh_GasExplosionBlueEmitter.frustumCulled = false;
            this.scene.add(mesh_GasExplosionBlueEmitter);
            this.mesh_GasExplosionBlueEmitter = mesh_GasExplosionBlueEmitter;

            const frm_arr = new Float32Array(cnt_GasExplosionBlueEmitter);
            const opc_arr = new Float32Array(cnt_GasExplosionBlueEmitter);
            const clr_arr = new Float32Array(cnt_GasExplosionBlueEmitter * 3);
            mesh_GasExplosionBlueEmitter.geometry.setAttribute("aFrame", new THREE.InstancedBufferAttribute(frm_arr, 1));
            mesh_GasExplosionBlueEmitter.geometry.setAttribute("aOpacity", new THREE.InstancedBufferAttribute(opc_arr, 1));
            mesh_GasExplosionBlueEmitter.geometry.setAttribute("aColor", new THREE.InstancedBufferAttribute(clr_arr, 3));
            frm_GasExplosionBlueEmitter = frm_arr;
            opc_GasExplosionBlueEmitter = opc_arr;
            clr_GasExplosionBlueEmitter = clr_arr;
            const vel_arr = new Float32Array(cnt_GasExplosionBlueEmitter * 3);
            const off_arr = new Float32Array(cnt_GasExplosionBlueEmitter * 3);
            mesh_GasExplosionBlueEmitter.geometry.setAttribute("aVelocity", new THREE.InstancedBufferAttribute(vel_arr, 3));
            mesh_GasExplosionBlueEmitter.geometry.setAttribute("aOffset", new THREE.InstancedBufferAttribute(off_arr, 3));
            vel_buf_GasExplosionBlueEmitter = vel_arr;
            off_buf_GasExplosionBlueEmitter = off_arr;
            for (let i = 0; i < cnt_GasExplosionBlueEmitter; i++) {
                this.life_GasExplosionBlueEmitter.push(1.0);
                this.maxLife_GasExplosionBlueEmitter.push(1.0);
                this.pos_GasExplosionBlueEmitter.push(new THREE.Vector3(x, y, z));
                this.vel_GasExplosionBlueEmitter.push(new THREE.Vector3(0, 0, 0));
                this.sz_GasExplosionBlueEmitter.push(0);
                this.rot_GasExplosionBlueEmitter.push(0);
            }
        } else {
            mesh_GasExplosionBlueEmitter = this.mesh_GasExplosionBlueEmitter;
            mesh_GasExplosionBlueEmitter.visible = true;
            geo_GasExplosionBlueEmitter = this.geo_GasExplosionBlueEmitter!;
            frm_GasExplosionBlueEmitter = mesh_GasExplosionBlueEmitter.geometry.getAttribute("aFrame").array as Float32Array;
            opc_GasExplosionBlueEmitter = mesh_GasExplosionBlueEmitter.geometry.getAttribute("aOpacity").array as Float32Array;
            clr_GasExplosionBlueEmitter = mesh_GasExplosionBlueEmitter.geometry.getAttribute("aColor").array as Float32Array;
            vel_buf_GasExplosionBlueEmitter = mesh_GasExplosionBlueEmitter.geometry.getAttribute("aVelocity").array as Float32Array;
            off_buf_GasExplosionBlueEmitter = mesh_GasExplosionBlueEmitter.geometry.getAttribute("aOffset").array as Float32Array;
        }

        // Reset particle arrays in place
        for (let i = 0; i < cnt_GasExplosionBlueEmitter; i++) {
            this.life_GasExplosionBlueEmitter[i] = 1.0;
            this.maxLife_GasExplosionBlueEmitter[i] = 1.0;
            this.pos_GasExplosionBlueEmitter[i].set(x, y, z);
            this.vel_GasExplosionBlueEmitter[i].set(0, 0, 0);
            this.sz_GasExplosionBlueEmitter[i] = 0;
            this.rot_GasExplosionBlueEmitter[i] = 0;
        }

        this.ptr_GasExplosionBlueEmitter = 0;
        this.spawnTimer_GasExplosionBlueEmitter = 0;

        const spawnParticle_GasExplosionBlueEmitter = (i: number) => {
            this.life_GasExplosionBlueEmitter[i] = 0;
            this.maxLife_GasExplosionBlueEmitter[i] = rng(0.17, 0.3);
            this.sz_GasExplosionBlueEmitter[i] = rng(2.2, 2.3);
            this.rot_GasExplosionBlueEmitter[i] = rng(0, Math.PI * 2);

            const theta = Math.random() * Math.PI * 2;
            const phi = Math.acos(rng(-1, 1));
            const speed = rng(0.1, 0.1) * 2.0;
            const srad = 0.01 * 2.0;
            this.pos_GasExplosionBlueEmitter[i].set(
                x + Math.sin(phi) * Math.cos(theta) * srad,
                y + Math.sin(phi) * Math.sin(theta) * srad,
                z + Math.cos(phi) * srad,
            );
            this.vel_GasExplosionBlueEmitter[i].set(
                Math.sin(phi) * Math.cos(theta) * speed,
                Math.sin(phi) * Math.sin(theta) * speed,
                Math.cos(phi) * speed,
            );
        };

        // Trigger initial bursts
        const initialBurst_GasExplosionBlueEmitter = 2;
        for (
            let i = 0;
            i <
            Math.min(
                cnt_GasExplosionBlueEmitter,
                initialBurst_GasExplosionBlueEmitter,
            );
            i++
        ) {
            spawnParticle_GasExplosionBlueEmitter(this.ptr_GasExplosionBlueEmitter);
            this.ptr_GasExplosionBlueEmitter =
                (this.ptr_GasExplosionBlueEmitter + 1) % cnt_GasExplosionBlueEmitter;
        }

        const colorKeys_GasExplosionBlueEmitter: ColorKey[] | null = [
            { value: { r: 1.0, g: 1.0, b: 1.0 }, pos: 0.0 },
            { value: { r: 0.44314, g: 0.95294, b: 1.0 }, pos: 1.0 },
        ];
        const alphaKeys_GasExplosionBlueEmitter: AlphaKey[] | null = [
            { value: 1.0, pos: 0.0 },
            { value: 1.0, pos: 0.90001 },
        ];

        // Update closure captured for this emitter
        const update_GasExplosionBlueEmitter = (dt: number) => {
            // Spawn particles continuously over time
            const rate = 0;
            if (rate > 0) {
                this.spawnTimer_GasExplosionBlueEmitter += dt;
                const interval = 1.0 / rate;
                while (this.spawnTimer_GasExplosionBlueEmitter >= interval) {
                    spawnParticle_GasExplosionBlueEmitter(
                        this.ptr_GasExplosionBlueEmitter,
                    );
                    this.ptr_GasExplosionBlueEmitter =
                        (this.ptr_GasExplosionBlueEmitter + 1) %
                        cnt_GasExplosionBlueEmitter;
                    this.spawnTimer_GasExplosionBlueEmitter -= interval;
                }
            }

            for (let i = 0; i < cnt_GasExplosionBlueEmitter; i++) {
                if (
                    this.life_GasExplosionBlueEmitter[i] >=
                    this.maxLife_GasExplosionBlueEmitter[i]
                ) {
                    mesh_GasExplosionBlueEmitter.setMatrixAt(i, hideM);
                    opc_GasExplosionBlueEmitter[i] = 0;
                    continue;
                }
                this.life_GasExplosionBlueEmitter[i] += dt;
                const pct = Math.min(
                    1,
                    this.life_GasExplosionBlueEmitter[i] /
                        this.maxLife_GasExplosionBlueEmitter[i],
                );
                if (
                    this.life_GasExplosionBlueEmitter[i] >=
                    this.maxLife_GasExplosionBlueEmitter[i]
                ) {
                    mesh_GasExplosionBlueEmitter.setMatrixAt(i, hideM);
                    opc_GasExplosionBlueEmitter[i] = 0;
                    continue;
                }
                // Physics: gravity + drag
                this.vel_GasExplosionBlueEmitter[i].y += 0 * dt;

                const speed_GasExplosionBlueEmitter =
                    this.vel_GasExplosionBlueEmitter[i].length();
                const limit_GasExplosionBlueEmitter = 0 * 2.0;
                if (
                    speed_GasExplosionBlueEmitter >
                    limit_GasExplosionBlueEmitter
                ) {
                    const percent =
                        (speed_GasExplosionBlueEmitter -
                            limit_GasExplosionBlueEmitter) /
                        speed_GasExplosionBlueEmitter;
                    this.vel_GasExplosionBlueEmitter[i].multiplyScalar(
                        Math.max(0, 1 - percent * 0.09 * dt * 20),
                    );
                }

                this.pos_GasExplosionBlueEmitter[i].addScaledVector(
                    this.vel_GasExplosionBlueEmitter[i],
                    dt,
                );

                const sizeBez: PiecewiseCurve[] = [
                    {
                        start: 0,
                        end: 1,
                        p0: 0.58750004,
                        p1: 0.9525568066666666,
                        p2: 1,
                        p3: 1,
                    },
                ];
                const scaledSz =
                    this.sz_GasExplosionBlueEmitter[i] *
                    2.0 *
                    evalPiecewise(sizeBez, pct);

                const alpha = alphaKeys_GasExplosionBlueEmitter
                    ? evalAlpha(alphaKeys_GasExplosionBlueEmitter, pct)
                    : 1 - pct;
                const col = colorKeys_GasExplosionBlueEmitter
                    ? evalColor(colorKeys_GasExplosionBlueEmitter, pct)
                    : { r: 1, g: 1, b: 1 };

                T.position.set(0, 0, 0);
                T.quaternion.set(0, 0, 0, 1);

                // StretchedBillboard: shader handles orientation via aVelocity/aOffset
                T.scale.setScalar(scaledSz);
                off_buf_GasExplosionBlueEmitter[i * 3 + 0] =
                    this.pos_GasExplosionBlueEmitter[i].x;
                off_buf_GasExplosionBlueEmitter[i * 3 + 1] =
                    this.pos_GasExplosionBlueEmitter[i].y;
                off_buf_GasExplosionBlueEmitter[i * 3 + 2] =
                    this.pos_GasExplosionBlueEmitter[i].z;
                vel_buf_GasExplosionBlueEmitter[i * 3 + 0] =
                    this.vel_GasExplosionBlueEmitter[i].x * 1.0;
                vel_buf_GasExplosionBlueEmitter[i * 3 + 1] =
                    this.vel_GasExplosionBlueEmitter[i].y * 1.0;
                vel_buf_GasExplosionBlueEmitter[i * 3 + 2] =
                    this.vel_GasExplosionBlueEmitter[i].z * 1.0;

                T.updateMatrix();
                mesh_GasExplosionBlueEmitter.setMatrixAt(i, T.matrix);

                const frameBez: PiecewiseCurve[] = [
                    {
                        start: 0,
                        end: 1,
                        p0: 0,
                        p1: 3,
                        p2: 6.000000000000001,
                        p3: 9,
                    },
                ];
                const frameRaw = evalPiecewise(frameBez, pct);
                frm_GasExplosionBlueEmitter[i] = Math.min(
                    8,
                    Math.floor(frameRaw),
                );
                opc_GasExplosionBlueEmitter[i] = alpha;
                clr_GasExplosionBlueEmitter[i * 3 + 0] = col.r * cfgColor.r;
                clr_GasExplosionBlueEmitter[i * 3 + 1] = col.g * cfgColor.g;
                clr_GasExplosionBlueEmitter[i * 3 + 2] = col.b * cfgColor.b;
                mesh_GasExplosionBlueEmitter.geometry.attributes.aVelocity.needsUpdate = true;
                mesh_GasExplosionBlueEmitter.geometry.attributes.aOffset.needsUpdate = true;
            }
            mesh_GasExplosionBlueEmitter.instanceMatrix.needsUpdate = true;
            (
                mesh_GasExplosionBlueEmitter.geometry.getAttribute(
                    "aFrame",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
            (
                mesh_GasExplosionBlueEmitter.geometry.getAttribute(
                    "aOpacity",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
            (
                mesh_GasExplosionBlueEmitter.geometry.getAttribute(
                    "aColor",
                ) as THREE.InstancedBufferAttribute
            ).needsUpdate = true;
        };

        cleanups.push(() => {
            mesh_GasExplosionBlueEmitter.visible = false;
        });

        // ── Main animation tick ───────────────────────────────────────
        this.activeFX.push({
            update: (dt: number) => {
                this.age += dt;
                if (this.age > 2) {
                    cleanups.forEach((fn) => fn());
                    return false;
                }
                const cq = this.camera.quaternion;
                void cq;
                update_SparksEmitter(dt);
                update_GlowEmitter(dt);
                update_CloudBurstEmitter(dt);
                update_TrailEmitter(dt);
                update_SmokeTrailEmitter(dt);
                update_GasExplosionBlueEmitter(dt);
                return true;
            },
        });
    }

    public update(delta: number) {
        for (let i = this.activeFX.length - 1; i >= 0; i--) {
            if (!this.activeFX[i].update(delta)) this.activeFX.splice(i, 1);
        }
    }
}

export class CartoonBlueGasExplosionNativeVFX {
    private scene: THREE.Scene;
    private camera: THREE.Camera;
    private mesh: THREE.InstancedMesh;
    private maxParticles = 250;
    
    private pPos: Float32Array; // [x,y,z]
    private pVel: Float32Array; // [vx,vy,vz]
    private pAge: Float32Array; // [age]
    private pMaxLife: Float32Array; // [maxLife]
    private pActive: Uint8Array; // [active_flag]
    private nextPtr = 0;

    constructor(scene: THREE.Scene, camera: THREE.Camera) {
        this.scene = scene;
        this.camera = camera;

        // Create a single simple geometry and flat material with additive blending (super lightweight)
        const geo = new THREE.PlaneGeometry(0.35, 0.35);
        const mat = new THREE.MeshBasicMaterial({
            color: 0x00dfff,
            transparent: true,
            blending: THREE.AdditiveBlending,
            depthWrite: false,
            side: THREE.DoubleSide
        });

        this.mesh = new THREE.InstancedMesh(geo, mat, this.maxParticles);
        this.mesh.frustumCulled = false;
        
        // Hide all initially
        const hideM = new THREE.Matrix4().makeScale(0, 0, 0);
        for (let i = 0; i < this.maxParticles; i++) {
            this.mesh.setMatrixAt(i, hideM);
        }
        this.mesh.instanceMatrix.needsUpdate = true;
        this.scene.add(this.mesh);

        // Pre-allocated arrays
        this.pPos = new Float32Array(this.maxParticles * 3);
        this.pVel = new Float32Array(this.maxParticles * 3);
        this.pAge = new Float32Array(this.maxParticles);
        this.pMaxLife = new Float32Array(this.maxParticles);
        this.pActive = new Uint8Array(this.maxParticles);
    }

    public spawn(x: number, y: number, z: number) {
        // Spawn 4 tiny quick spark particles per hit (minimal GPU fillrate / overdraw)
        for (let k = 0; k < 4; k++) {
            const idx = this.nextPtr;
            this.nextPtr = (this.nextPtr + 1) % this.maxParticles;

            this.pActive[idx] = 1;
            this.pAge[idx] = 0;
            this.pMaxLife[idx] = 0.15 + Math.random() * 0.15; // very fast fade out

            const pIdx = idx * 3;
            this.pPos[pIdx] = x;
            this.pPos[pIdx+1] = y + 0.5; // shift to torso height
            this.pPos[pIdx+2] = z;

            // Explode outwards in random directions
            const theta = Math.random() * Math.PI * 2;
            const phi = Math.acos((Math.random() * 2) - 1);
            const speed = 2.0 + Math.random() * 3.0;

            this.pVel[pIdx] = Math.sin(phi) * Math.cos(theta) * speed;
            this.pVel[pIdx+1] = Math.sin(phi) * Math.sin(theta) * speed + 1.0; // slight upward drift
            this.pVel[pIdx+2] = Math.cos(phi) * speed;
        }
    }

    public update(delta: number) {
        const camQ = this.camera.quaternion;
        const dummy = new THREE.Object3D();
        const hideM = new THREE.Matrix4().makeScale(0, 0, 0);
        let needsUpdate = false;

        for (let i = 0; i < this.maxParticles; i++) {
            if (this.pActive[i] === 0) continue;

            this.pAge[i] += delta;
            if (this.pAge[i] >= this.pMaxLife[i]) {
                this.pActive[i] = 0;
                this.mesh.setMatrixAt(i, hideM);
                needsUpdate = true;
                continue;
            }

            needsUpdate = true;
            const pIdx = i * 3;
            
            // Move particle
            this.pPos[pIdx] += this.pVel[pIdx] * delta;
            this.pPos[pIdx+1] += this.pVel[pIdx+1] * delta;
            this.pPos[pIdx+2] += this.pVel[pIdx+2] * delta;

            // Render billboarding toward camera
            dummy.position.set(this.pPos[pIdx], this.pPos[pIdx+1], this.pPos[pIdx+2]);
            dummy.quaternion.copy(camQ);
            
            // Shrink over time
            const lifeRatio = 1.0 - (this.pAge[i] / this.pMaxLife[i]);
            dummy.scale.setScalar(lifeRatio * 0.8);
            dummy.updateMatrix();

            this.mesh.setMatrixAt(i, dummy.matrix);
        }

        if (needsUpdate) {
            this.mesh.instanceMatrix.needsUpdate = true;
        }
    }
}
